table 'Base Measures'
	lineageTag: 0e1114f9-0d79-4362-87ae-3edafb9e5d2b

	measure #Orders = COUNTROWS(Sales)
		formatString: 0
		lineageTag: 49ebaf82-b0da-4b90-a6b8-5da108da32e2

	partition 'Base Measures' = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

