table Customer
	lineageTag: fe670d6d-3301-47e7-9255-092b64790ee2

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 379bb7ea-7daa-444a-bf6a-369444b27b71
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: cab4c703-8766-400f-91c1-b0f69c961f98
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 6e1ff596-ddde-4ec0-af17-4b08e8844349
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: a41e9ccc-b636-4abf-ba36-02778cb906f2
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 94849003-2090-4854-ad4c-37897cc100ee
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: ac87f09f-259a-43db-8155-6829f37af141
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 05163bae-3bf8-4cba-807f-95394bddb606
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column YearlyIncome
		dataType: int64
		formatString: 0
		lineageTag: 1e24c32e-83d0-42ff-8be9-5a59c2291d1e
		summarizeBy: none
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 0f427227-4257-424b-afa4-597f4b61bea5
		summarizeBy: none
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column NumberChildrenAtHome
		dataType: int64
		formatString: 0
		lineageTag: f5e73d26-2822-43e5-aa14-7f0583fc4b9e
		summarizeBy: none
		sourceColumn: NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column EnglishEducation
		dataType: string
		lineageTag: 26327b5c-7078-46fb-93c4-9f2fc69813c1
		summarizeBy: none
		sourceColumn: EnglishEducation

		annotation SummarizationSetBy = Automatic

	column EnglishOccupation
		dataType: string
		lineageTag: 4d81444b-748b-440a-b8bb-d0ec2b4e94f0
		summarizeBy: none
		sourceColumn: EnglishOccupation

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: int64
		formatString: 0
		lineageTag: aa8d3fef-baf5-4387-88a3-a8bc9becc8e0
		summarizeBy: none
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: e0cf1dcc-8c1a-47cd-9b7e-74b6ff0fda69
		summarizeBy: none
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column DateFirstPurchase
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0403238-323c-4dc5-9c22-c450bc8c2d3e
		summarizeBy: none
		sourceColumn: DateFirstPurchase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column City
		dataType: string
		lineageTag: 13828549-3b86-4bb0-8a90-9062b7477c1f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 989cf265-c02b-48af-ad07-65721ef0d5d9
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 21c5e499-1c81-4454-a661-f8d4aeeef7c8
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		lineageTag: 3c8611b1-69f3-4fe0-977b-aab25766ccdd
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrator.ADVENTUREWORKS\Desktop\Folder Sources\Aworks\DimCustomer.csv"),[Delimiter=",", Columns=29, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"GeographyKey", Int64.Type}, {"CustomerAlternateKey", type text}, {"Title", type text}, {"FirstName", type text}, {"MiddleName", type text}, {"LastName", type text}, {"NameStyle", Int64.Type}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Suffix", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"YearlyIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"NumberChildrenAtHome", Int64.Type}, {"EnglishEducation", type text}, {"SpanishEducation", type text}, {"FrenchEducation", type text}, {"EnglishOccupation", type text}, {"SpanishOccupation", type text}, {"FrenchOccupation", type text}, {"HouseOwnerFlag", Int64.Type}, {"NumberCarsOwned", Int64.Type}, {"AddressLine1", type text}, {"AddressLine2", type text}, {"Phone", type text}, {"DateFirstPurchase", type date}, {"CommuteDistance", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"GeographyKey"}, Geography, {"GeographyKey"}, "Geography", JoinKind.LeftOuter),
				    #"Expanded Geography" = Table.ExpandTableColumn(#"Merged Queries", "Geography", {"City", "State", "Country", "PostalCode"}, {"City", "State", "Country", "PostalCode"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded Geography",{"CustomerKey", "GeographyKey", "FirstName", "LastName", "BirthDate", "MaritalStatus", "Gender", "YearlyIncome", "TotalChildren", "NumberChildrenAtHome", "EnglishEducation", "EnglishOccupation", "HouseOwnerFlag", "NumberCarsOwned", "DateFirstPurchase", "City", "State", "Country", "PostalCode"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

