table Sales
	lineageTag: 07c0fe99-9c93-4b4f-bc9a-065ca5ea4afd

	column SalesOrderNumber
		dataType: string
		lineageTag: 8186f5fc-c0ff-47e2-a8d5-8f98e7fda8d8
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 1ccc5ff2-f9e4-4bcd-8cd1-2f52339c3abc
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 630724e3-1b17-4e06-938e-a7cfa546f025
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a20ee559-134a-4303-b08e-7751348e8dda
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2998726e-a305-4ce6-b238-3f59b282cdb6
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 6c53f20d-e92c-45a9-9246-c778699a5686
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: c4fe5f70-941b-4a5e-b7e5-6638f1fa856a
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: eb3e4e67-bb4e-4732-b1ae-5f78d9aeb186
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: e12a6d7f-571a-4dbd-a1fe-b90bb17b75d5
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedAmount
		dataType: double
		lineageTag: d27789f1-fa47-454f-9d58-f944e57a250e
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: int64
		formatString: 0
		lineageTag: 797ec55e-0952-4178-817c-bd3ea5c94d5e
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

	column DiscountAmount
		dataType: int64
		formatString: 0
		lineageTag: ffcf4531-db7c-4150-bc1a-2b01296bbbe1
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

	column ProductStandardCost
		dataType: double
		lineageTag: 9c43e722-d06f-4cb5-abcd-4f81ddfa3264
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalProductCost
		dataType: double
		lineageTag: 2140dbdd-4d7d-41f7-b27e-87c8745031e9
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		lineageTag: c3357163-58d4-4220-a135-468442c5d51b
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TaxAmt
		dataType: double
		lineageTag: c802b660-9de3-4ecb-bc79-9101203d361d
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Freight
		dataType: double
		lineageTag: b6722d7a-f57f-4f7a-9b20-ad720add0720
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Name'
		dataType: string
		lineageTag: f7016f58-b845-4ab5-95d3-e0f41b5b217d
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Start of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5dc19be3-19e0-42d6-950f-3b5114eb5be1
		summarizeBy: none
		sourceColumn: Start of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 72ac2961-bfdc-4af4-b965-b4f18ea9e32f
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrator.ADVENTUREWORKS\Desktop\Folder Sources\Aworks\FactInternetSales.csv"),[Delimiter=",", Columns=22, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesOrderNumber", type text}, {"SalesOrderLineNumber", Int64.Type}, {"OrderDate", type date}, {"DueDate", type date}, {"ShipDate", type date}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"PromotionKey", Int64.Type}, {"CurrencyKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"OrderQuantity", Int64.Type}, {"UnitPrice", type number}, {"ExtendedAmount", type number}, {"UnitPriceDiscountPct", Int64.Type}, {"DiscountAmount", Int64.Type}, {"ProductStandardCost", type number}, {"TotalProductCost", type number}, {"SalesAmount", type number}, {"TaxAmt", type number}, {"Freight", type number}, {"CarrierTrackingNumber", type text}, {"CustomerPONumber", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"PromotionKey", "CurrencyKey", "SalesTerritoryKey", "CarrierTrackingNumber", "CustomerPONumber"}),
				    #"Rounded Off" = Table.TransformColumns(#"Removed Columns",{{"UnitPrice", each Number.Round(_, 1), type number}, {"ExtendedAmount", each Number.Round(_, 1), type number}}),
				    #"Rounded Off1" = Table.TransformColumns(#"Rounded Off",{{"ProductStandardCost", each Number.Round(_, 1), type number}, {"TotalProductCost", each Number.Round(_, 1), type number}, {"SalesAmount", each Number.Round(_, 1), type number}, {"TaxAmt", each Number.Round(_, 1), type number}, {"Freight", each Number.Round(_, 1), type number}}),
				    #"Split Column by Character Transition" = Table.SplitColumn(#"Rounded Off1", "SalesOrderNumber", Splitter.SplitTextByCharacterTransition((c) => not List.Contains({"0".."9"}, c), {"0".."9"}), {"SalesOrderNumber.1", "SalesOrderNumber.2"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Split Column by Character Transition",{"SalesOrderNumber.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"SalesOrderNumber.2", "SalesOrderNumber"}}),
				    #"Inserted Month Name" = Table.AddColumn(#"Renamed Columns", "Month Name", each Date.MonthName([OrderDate]), type text),
				    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Month Name", "Start of Quarter", each Date.StartOfQuarter([OrderDate]), type date),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Inserted Start of Quarter", "OrderDate", "OrderDate - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"OrderDate - Copy", "Year"}}),
				    #"Extracted Year" = Table.TransformColumns(#"Renamed Columns1",{{"Year", Date.Year, Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Extracted Year", each [Year] >= PYearStart and [Year] < PYearEnd)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

