table 'Base Measures'
	lineageTag: ef7950c0-d31a-492e-ac76-bdd9800eef55

	measure #Orders = COUNTROWS(Sales)
		formatString: 0
		lineageTag: 94eacb6f-cd2f-407d-8159-944c22ec0040

	measure OrderQTY = Sum(Sales[OrderQuantity])
		formatString: 0
		lineageTag: 2762eb02-67eb-44e8-a71a-a4aee287c744

	measure Revenue = SUM(Sales[SalesAmount])
		lineageTag: 17628f28-2a36-4dce-bd97-2f5c5677ccdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Base Measures' = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

